apiVersion: v1
kind: Service
metadata:
  name: program1-service
  labels:
    app: program1
spec:
  selector:
    app: program1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 6000
  type: LoadBalancer
